#!/usr/bin/env bash

origin=$(git config "remote.origin.url") || exit $?
upstream=$(git config "remote.upstream.url") || exit $?

#what is the name in the upstream
substart=`awk -v a="${upstream}" -v b=":" 'BEGIN{print index(a,b)}'`
subend=`awk -v a="${upstream}" -v b="/" 'BEGIN{print index(a,b)}'`

upstream=`echo ${upstream} | cut -c$((substart+1))-$((subend-1))`

# format the orgin to be a github url
origin=${origin/://}
origin=${origin/git@/http://}
origin=${origin/.git/}

link=$(git for-each-ref --format=':%(upstream:short)...%(refname:short)' refs/heads/6_4_3-Bug43663-WorkflowModuleHotfix)

url=$origin"/compare/"$upstream$link

if which xdg-open > /dev/null; then
  xdg-open $url
elif which gnome-open > /dev/null; then
  gnome-open $url
else
  # just try and open comand
  open $url
fi
